### PR TITLE
Fix extension crash on iOS 13

### LINKED ISSUE #67: Main app is not opened on iOS 13
I tested my app which is perfectly working on iOS 12 on a iOS 13 beta device. The main app is not opened after sharing. If I open the app manually the handler is called and the file exists.

This is the error on the Xcode console
```
2019-09-03 16:24:28.710199+0200 ShareExt[456:13928] -[__NSDictionary0 universalLinksOnly]: unrecognized selector sent to instance 0x1d08f9568
2019-09-03 16:24:28.710707+0200 ShareExt[456:13928] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionary0 universalLinksOnly]: unrecognized selector sent to instance 0x1d08f9568'
*** First throw call stack:
(0x194bf3b64 0x19491c0a4 0x194af7658 0x194bf7f48 0x194bf9cec 0x198248b54 0x194bf9e90 0x194ac9ef8 0x10256eba8 0x10256f2d0 0x194fe93f0 0x1948c0610 0x1948c1184 0x19486d464 0x19486de58 0x194877340 0x194910fa4 0x194913ae0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Looks like the opening of the URL does not work. The strange thing is the error with "universalLinksOnly". Does this means we must switch from a custom scheme to a Universal link. I guess the problem is somewhere in the URL open method: https://github.com/j3k0/cordova-plugin-openwith/blob/e1fcc02e08b5580178b7a5dbb292ec2962fb1ac1/src/ios/ShareExtension/ShareViewController.m#L79-L105

@j3k0 Do you know some more about that method from the initial development? Something must have changed on iOS 13.

Does anybody else have this issue?

### PR DESCRIPTION
**Pull request by NiklasMerz**
Changing the options seems to fix the crash on iOS 13. Then strange thing is that this seems to work on iOS 12 aswell when built with Xcode 11. Working with `@available`and the old option did not work for me and now it shows warnings because the new optiosn are on iOS 13 only. No idea why.

This "fix" needs Xcode 11 so we should wait before merging this to a new version.

Fixes #67

### CODE REVIEW

File: src/ios/ShareExtension/ShareViewController.m [hunk 1]
```diff
@@ -88,7 +88,8 @@ - (void) openURL:(nonnull NSURL *)url {
             NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:methodSignature];
 
             // Arguments
-            NSDictionary<NSString *, id> *options = [NSDictionary dictionary];
+            UISceneOpenExternalURLOptions * options = [UISceneOpenExternalURLOptions alloc];
```
Comment (j3k0) [inline src/ios/ShareExtension/ShareViewController.m]: The pattern in obj-c is generally `[[Class alloc] init]`. Are you sure a call to `init` isn't missing here? This might let the object fields uninitialized.

Comment (NiklasMerz) [reply src/ios/ShareExtension/ShareViewController.m]: Good catch. I missed that.

**Comment by NiklasMerz** [comment]
@j3k0 As this only works in Xcode 11 and newer how do we implement this? Use build flags? I am not that familiar with this. New major version? 

Do you have time to look into this?

We also need version checks for iOS 13. At least there is a warning for that. But this new code works for me on iOS 12.4. That doesn't really make sense to me. And I don't really know how to make this version check in a good way.

**Comment by NiklasMerz** [comment]
This is my attempt to check version. There has to be a cleaner version.

**Comment by NiklasMerz** [comment]
@EternallLight Would you like to review and/or test this?

**Comment by j3k0** [comment]
Hey Niklas,


Looked into the code, this should be fine (I think the `@available` 
thing requires XCode 9, this is fine, Apple is quickly requiring devs to 
build against the latest SDK to get apps approved, so all devs must be 
mostly up-to-date). I'm sorry I don't have much time to test this code 
though (no test bed in place). I'm super busy at least till the end of 
the month.

Feel free to merge as you please, you're really the main maintainer of 
this project.


JC

**Comment by NiklasMerz** [comment]
Thank you for testing.

**Comment by AlexanderHieser** [comment]
Hi, 

i tested the fix on iOS 13 as well as on iOS 12.4. Works without any issues 👍

**Comment by NiklasMerz** [comment]
@j3k0 I am thinking about doing a new release with this fix. Since this is a breaking change (requiring Xcode 11), should we do a major relase (2.0)?

**Comment by j3k0** [comment]
Hey @NiklasMerz, happy new year :)

I agree, doing a major release seems appropriate. Do you have `npm publish` permission or do you want help from me?

**Comment by j3k0** [comment]
https://github.com/j3k0/cordova-plugin-openwith/pull/72 seems good to include too in the new release.

**Comment by NiklasMerz** [comment]
Happy new year. Yes I have NPM permission and will do the release right now.

**Comment by NiklasMerz** [comment]
Version 2.0 is released. https://github.com/j3k0/cordova-plugin-openwith/releases/tag/v2.0.0

I just did a mistake, I had to revert. I checked in package-lock.json that's why the dependabot PR's opened. @j3k0 Should we check package-lock.json in to git and update the dependencies?

**Comment by j3k0** [comment]
@NiklasMerz as far as I know. `package-lock.json` files should NOT be checked in git for libraries, only for apps.

**Comment by NiklasMerz** [comment]
Good to know. Then we could add it to gitignore
